# PostgreSQL. Versions 7.4 and 8.x are supported.

development:
  adapter: postgresql
  encoding: utf8
  database: job_board_dev
  pool: 5
  username: job_board_dev
  password: lockbox7

test:
  adapter: postgresql
  encoding: utf8
  database: job_board_test
  pool: 5
  username: job_board_test
  password: lockbox7

production:
  adapter: postgresql
  encoding: utf8
  database: job_board_production
  pool: 5
  username: job_board_production
  password: lockbox7
